app/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users'))
]

handler404 = views.page_not_found

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('prices/', views.prices, name='prices'),
    path('new-order/', views.NewOrderView.as_view(), name='new-order'),
    path('contacts/', views.contacts, name='contacts'),
    path('accept/', views.AcceptOrderView.as_view(), name='accept'),
    path('accept/done/', views.AcceptOrderDoneView.as_view(), name='accept-done')
]

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView
from django.urls import path, reverse_lazy

from users import views
from users.views import UserPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('registration/', views.AuthRegistrationView.as_view(), name='registration'),
    path('logout/', views.logout, name='logout'),
    path('profile/<pk>', views.UserProfileView.as_view(), name='profile'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password-reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password-reset-done.html'
         ),
         name='password-reset-done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password-reset-confirm.html',
            success_url=reverse_lazy('users:password-reset-complete')
         ),
         name='password-reset-confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password-change-done.html'
         ),
         name='password-reset-complete'),

    path('password-change/',
         UserPasswordChangeView.as_view(
             template_name='users/password-change-form.html'
         ),
         name='password-change'),

    path('password-change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password-change-done.html'
         ),
         name='password-change-done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserModel(AbstractUser):

    first_name = models.CharField(
        max_length=20, verbose_name='Имя', blank=True, null=True
    )
    last_name = models.CharField(
        max_length=20, verbose_name='Фамилия', blank=True, null=True
    )

    class Meta:
        db_table = 'user'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import UserModel
from users.services import ValidateNameMixin


class LoginForm(AuthenticationForm):
    class Meta:
        model = UserModel


class RegistrationForm(UserCreationForm):

    username = forms.CharField(
        min_length=3,
        max_length=16,
        label='Имя пользователя'
    )
    email = forms.EmailField(label='Email')
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].error_messages.update(self.length_msg(3, 16))

    class Meta:
        model = UserModel
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        msg = {'email': 'Пользователь с таким Email уже существует.'}

        if email and self._meta.model.objects.filter(email=email).exists():
            self._update_errors(forms.ValidationError(msg))
        else:
            return email

    @staticmethod
    def length_msg(min_len: int, max_len: int) -> dict:
        return {
            'min_length': f'Минимальноe количество символов - {min_len}',
            'max_length': f'Максимальное количество символов - {max_len}'
        }


class ProfileForm(ValidateNameMixin, UserChangeForm):

    class Meta:
        model = UserModel
        fields = 'first_name', 'last_name', 'email'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.data.get('username')
        msg = {'email': 'Пользователь с таким Email уже существует.'}
        user = UserModel.objects.filter(email=email).exclude(username=username)

        if user:
            self._update_errors(forms.ValidationError(msg))
        else:
            return email

    def clean_first_name(self):
        return self.check_name(self, 'first_name') or None

    def clean_last_name(self):
        return self.check_name(self, 'last_name') or None

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, reverse, render
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import FormView, CreateView, UpdateView
from django.http import HttpResponse, JsonResponse

from app.settings import DEBUG
from logger import Logger
from main.application.services.commands.delete_order import DeleteOrder
from main.application.services.commands.get_orders import GetOrders
from main.exceptions import OrderNotFoundException
from shared.infrastructure.uow import UnitOfWork, TestUnitOfWork
from users.application.command.auth_user import AuthUser
from users.application.command.delete_user import DeleteUser
from users.forms import LoginForm, RegistrationForm, ProfileForm
from users.models import UserModel


class AuthLoginView(FormView):
    form_class = LoginForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    auth = auth
    auth_user_command = AuthUser()

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']
        self.auth_user_command(auth, self.request, username, password)
        return JsonResponse({'status': 'ok'}, status=200)

    def form_invalid(self, form):
        errors = form.errors.get_json_data()
        return JsonResponse({'errors': errors}, status=400)


class AuthRegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'users/registration.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('main:home')
    auth = auth
    auth_user_command = AuthUser()

    def form_valid(self, form):
        super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        self.auth_user_command(auth, self.request, username, password)
        return JsonResponse({'status': 'ok'}, status=200)

    def form_invalid(self, form):
        errors = form.errors.get_json_data()
        return JsonResponse({'errors': errors}, status=400)


class UserProfileView(LoginRequiredMixin, UpdateView):
    model = UserModel
    form_class = ProfileForm
    template_name = 'users/profile.html'
    logger = Logger()
    get_orders_command = GetOrders(logger)
    delete_user_command = DeleteUser(logger)
    delete_order_command = DeleteOrder(logger)
    uow = UnitOfWork() if not DEBUG else TestUnitOfWork()

    def form_valid(self, form, **kwargs):
        form.save()
        return JsonResponse({'message': 'Данные успешно изменены'}, status=200)

    def form_invalid(self, form):
        errors = form.errors.get_json_data()
        return JsonResponse({'errors': errors}, status=400)

    def get(self, request, *args, **kwargs):
        if kwargs['pk'] != str(self.request.user.pk):
            return HttpResponse(status=404)

        remove_order_id = request.GET.get('remove-order')
        if remove_order_id:
            try:
                self.delete_order_command(self.uow, self.request.user.pk, int(remove_order_id))
                return redirect('users:profile', pk=request.user.pk)
            except OrderNotFoundException:
                return HttpResponse(status=404)

        if request.GET.get('remove-user'):
            self.delete_user_command(self.uow, self.request.user)
            return redirect('main:home')

        context = {
            'title': 'Профиль',
            'orders': self.get_orders_command(self.uow, self.request.user),
        }
        return render(request, 'users/profile.html', context=context)

    def get_success_url(self):
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:home'))


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'users/password-change-form.html'

    def form_valid(self, form, **kwargs):
        form.save()
        return JsonResponse({'status': 'ok'}, status=200)

    def form_invalid(self, form):
        errors = form.errors.get_json_data()
        return JsonResponse({'errors': errors}, status=400)


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password-reset-form.html'
    email_template_name = 'users/password-reset-email.html'
    html_email_template_name = 'users/password-reset-email.html'
    success_url = reverse_lazy('users:password-reset-done')

    def form_valid(self, form):
        opts = {
            'use_https': self.request.is_secure(),
            'token_generator': self.token_generator,
            'from_email': self.from_email,
            'email_template_name': self.email_template_name,
            'subject_template_name': self.subject_template_name,
            'request': self.request,
            'html_email_template_name': self.html_email_template_name,
            'extra_email_context': self.extra_email_context,
        }
        form.save(**opts)

        return JsonResponse({'status': 'ok'}, status=200)

users/templates/users/base-profile.html
{% extends 'main/base.html' %}
{% load static %}
{% load users_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_my_orders.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
  <div class="logo-container">
      <div class="form-wrapper">
          <div class="form-header form-font">Профиль</div>
          <div class="form-container-profile">
              <div class="form-font form-profile-wrapper">
                  <div class="logout-button">
                      <a href="{% url 'users:logout' %}" title="Выход"></a>
                  </div>
                  <div class="form-inner-wrapper">
                      <div class="username-container">
                          <p>{{ user.username }}</p>
                      </div>
                      {% block profile-form %}
                      {% endblock %}
                  </div>
              </div>
              <div class="form-orders-title form-font">
                  <p>История заказов</p>
                  <div class="search-button form-button">
                      <div class="search">
                          <form class="search-form">
                            <input class="search-form-input" type="number" name="search" placeholder="Номер заказа" id="id_search">
                            <button class="search-submit-button" type="submit">Поиск</button>
                          </form>
                      </div>
                      <span class="fa fa-search" aria-hidden="true"></span>
                  </div>
              </div>
              <div class="form-orders-wrapper">
                {% if orders %}
                <div class="card-wrapper">
                  {% for order in orders %}
                  <div class="card-container">
                    <div class="order-data">
                      <div class="order-number">
                        Заказ № {{ order.number }}
                      </div>
                        <div id="order-{{ order.number }}" class="order">
                          {% for product in order.products %}
                          <a>{{ product.title }}</a>
                          {% endfor %}
                        </div>
                      <div class="order-date">
                          <p>{{ order.date }}</p>
                          <p class="order-status">{{ order.status }}</p>
                      </div>
                    </div>
                    <a href="#orderModal" class="order-remove" data-bs-toggle="modal" title="Удалить">
                        <span class="fa fa-times" aria-hidden="true"></span>
                    </a>
                    <div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Вы уверены что хотите удалить заказ?</h5>
                              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-footer">
                                <form class="modal-form" action="{% url 'users:profile' user.pk %}" method="get">
                                  <input type="hidden" name="remove-order" value="{{ order.number }}">
                                  <button type="submit" class="form-button">Да</button>
                                  <button type="button" class="form-button" data-bs-dismiss="modal">Нет</button>
                                </form>
                            </div>
                          </div>
                        </div>
                    </div>
                    <div class="order-price">
                      <p> {{ order.total_price }}&#x20bd;</p>
                    </div>
                  </div>
                  {% endfor %}
                </div>
                {% else %}
                <div class="empty-order-list">
                    <p class="form-font">Список заказов пуст</p>
                    <a class="form-button" href="{% url 'main:new-order' %}"><span class="fa fa-plus-circle" aria-hidden="true"></span> Новый заказ</a>
                </div>
                {% endif %}
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_auth.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <div class="form-wrapper">
            <div class="form-header form-font">Вход</div>
            <div class="form-container">
                <form class="form-font" method="POST">
                    {% csrf_token %}
                    <div>
                        <div class="input-wrapper">
                            <div class="input-label-container">
                                <label for="id_username">{{ form.username.label }}:</label>
                                <div class="input-container">
                                    <div>
                                        <span class="fa fa-user-circle" aria-hidden="true"></span>
                                    </div>
                                    <input class="form-input"
                                           type="text"
                                           name="username"
                                           placeholder="{{ form.username.label }}"
                                           maxlength="32"
                                           required=""
                                           id="id_username"
                                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
                                </div>
                            </div>
                            <div class="error error-username"></div>
                        </div>
                    </div>
                    <div>
                        <div class="input-wrapper">
                            <div class="input-label-container">
                                <label for="id_password">{{ form.password.label }}: </label>
                                <div class="input-container">
                                    <div>
                                        <span class="fa fa-lock" aria-hidden="true"></span>
                                    </div>
                                    <input class="form-input"
                                           type="password"
                                           name="password"
                                           placeholder="{{ form.password.label }}"
                                           required=""
                                           id="id_password"
                                           value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
                                </div>
                            </div>
                            <div class="error" style="height: 24px">
                                <ul class="errorlist">
                                    <li class="error-nonfield"></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="login-error">
                    </div>
                    <div>
                        <div class="form-login-urls">
                            <a href="{% url 'users:password-reset' %}">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                        </div>
                    </div>
                    <button class="form-button" type="submit">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>    
    $(document).ready(function () {
          $('form').submit(function (e) {
              e.preventDefault();
              $.ajax({
                  data: $(this).serialize(),
                  type: $(this).attr('method'),
                  url: "{% url 'users:login' %}",
                  success: function () {
                      window.location.replace('{% url "main:home" %}');
                  },
                  error: function (response) {
                      $.each(response.responseJSON.errors, function (key, value) {
                          $.each(value, function () {
                              let errorText = $(this)[0].message
                              console.log(errorText)
                              if (errorText.includes('Пожалуйста')) {
                                  errorText = 'Пожалуйста, введите правильные имя пользователя и пароль.'
                              }
                              $('.error-nonfield').text(errorText).css('display', 'block').delay(5000).fadeOut(1000)
                          });
                      })
                  }
              });
              return false;
          });
    })
</script>
{% endblock %}

users/templates/users/password-change-done.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container form-font">
        <h1>Пароль изменен</h1>
        <p style="margin-top: 1em;">Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для входа в систему</p>
        <p style="margin-top: 1.5em;">
          <a class="form-button" href="{% url 'users:login' %}">Войти</a>
        </p>
    </div>
</div>
{% endblock %}

users/templates/users/password-reset-complete.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

users/templates/users/password-reset-done.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container form-font" style="width: 80%;">
        <h1>Сброс пароля</h1>
        <p style="margin-top: 1em;">Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты. Вы должны получить ее в ближайшее время.</p>
        <p style="margin-top: 0.5em;">Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base-profile.html' %}

{% block profile-form %}
<div class="profile-message">
    <p></p>
</div>
<form class="form-profile" action="{% url 'users:profile' user.pk %}" method="post">
{% csrf_token %}
  <div>
      <div class="input-wrapper">
          <div class="input-label-container">
              <input type="hidden" name="username" value="{{ user.username }}">
              <label for="id_first_name">Имя: </label>
              <div class="input-container">
                  <div>
                      <span class="fa fa-user-circle" aria-hidden="true"></span>
                  </div>
                  <input type="text"
                         class="form-input"
                         id="id_first_name"
                         name="first_name"
                         placeholder="Имя"
                         value="{% if user.first_name %}{{ user.first_name }}{% endif %}"
                         maxlength="20">
              </div>
          </div>
          <div class="error">
            <ul class="errorlist">
                <li class="error-first_name"></li>
            </ul>
          </div>
      </div>
  </div>
  <div>
      <div class="input-wrapper">
          <div class="input-label-container">
              <label for="id_last_name">Фамилия: </label>
              <div class="input-container">
                  <div>
                      <span class="fa fa-user-circle-o" aria-hidden="true"></span>
                  </div>
                  <input type="text"
                         class="form-input"
                         id="id_last_name"
                         name="last_name"
                         placeholder="Фамилия"
                         value="{% if user.last_name %}{{ user.last_name }}{% endif %}"
                         maxlength="20">
              </div>
          </div>
          <div class="error">
            <ul class="errorlist">
                <li class="error-last_name"></li>
            </ul>
          </div>
      </div>
  </div>
  <div>
      <div class="input-wrapper">
          <div class="input-label-container">
              <label for="id_email">Email: </label>
              <div class="input-container">
                  <div>
                      <span>@</span>
                  </div>
                  <input type="email"
                         class="form-input"
                         id="id_email"
                         name="email"
                         placeholder="Email"
                         value="{{ user.email }}"
                         required>
              </div>
          </div>
          <div class="error">
            <ul class="errorlist">
                <li class="error-email"></li>
            </ul>
          </div>
      </div>
  </div>
  <button type="submit" class="profile-save-button form-button">Сохранить</button>
  {% if change_pw_msg %}
  <p>{{ change_pw_msg }}</p>
  {% endif %}
</form>

<div class="profile-form-buttons-wrapper">
    <button type="button" class="form-button remove-user-button" data-bs-toggle="modal" data-bs-target="#removeUser">
      <span class="fa fa-ban" aria-hidden="true"></span> Удалить учётную запись
    </button>
    <a href="{% url 'users:password-change' %}" class="form-button change-pw-button">Сменить пароль</a>
</div>
<div class="modal fade" id="removeUser" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Вы уверены что хотите удалить свой профиль?</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
          <form class="modal-form" action="{% url 'users:profile' user.pk %}" method="get">
            <input type="hidden" name="remove-user" value="true">
            <button type="submit" class="form-button">Да</button>
            <button type="button" class="form-button" data-bs-dismiss="modal">Нет</button>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        let inputs = [];
        $.each($('.form-input'), function (){
            inputs.push($(this).val());
        });
        $('.form-profile').submit(function (e) {
            e.preventDefault();
            let newInputs = [];
            $.each($('.form-input'), function (){
                newInputs.push($(this).val());
            });
            if (inputs.toString() === newInputs.toString()) {
                return false;
            }
            inputs = newInputs
            $.ajax({
                data: $(this).serialize(),
                type: $(this).attr('method'),
                url: "{% url 'users:profile' user.pk %}",
                success: function (response) {
                    $('.profile-message p').css('display', 'block').text(response.message).delay(5000).fadeOut(1000);
                },
                error: function (response) {
                    $.each(response.responseJSON.errors, function (key, value) {
                        $('.error-'+key).text(value[0].message).css('display', 'block').delay(5000).fadeOut(1000);
                    })
                }
            });
            return false;
        });
    })
    const ordersList = []
    let orderObj

    {% if orders|length < 3 %}
    $('.form-orders-wrapper').css('overflow', 'hidden')
    {% endif %}

    {% for order in orders %}
      orderObj = {
        number: "{{ order.number }}",
        phoneNumber: "{{ order.phone_number }}",
        status: "{{ order.status }}",
        totalPrice: "{{ order.total_price }}",
        products: [],
        date: "{{ order.date }}"
      }
      {% for product in order.products %}
        orderObj.products.push(
          {
            code: "{{ product.code }}",
            name: "{{ product.name }}",
            title: "{{ product.title }}"
          }
        )
      {% endfor %}
      ordersList.push(orderObj)
    {% endfor %}
    $('.search-form').submit(function (e) {
      e.preventDefault()
      const searchValue = $('#id_search').val()
      const orders = ordersList.filter((order) => order.number.includes(searchValue))
      const cards = $('.card-wrapper')
      cards.empty()
      if (!orders.length) {
        cards.append(`
          <div class="empty-order-list">
            <p class="form-font">Список заказов пуст</p>
            <a class="form-button" href="{% url 'main:new-order' %}"><span class="fa fa-plus-circle" aria-hidden="true"></span> Новый заказ</a>
          </div>
        `)
        return false
      }
      orders.forEach(function (order) {
        cards.append(`
          <div class="card-container">
            <div class="order-data">
              <div class="order-number">
                Заказ № ${order.number}
              </div>
                <div id="order-${order.number}" class="order"></div>
              <div class="order-date">
                  <p>${order.date}</p>
                  <p class="order-status">${order.status}</p>
              </div>
            </div>
            <a href="#orderModal" class="order-remove" data-bs-toggle="modal" title="Удалить">
                <span class="fa fa-times" aria-hidden="true"></span>
            </a>
            <div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Вы уверены что хотите удалить заказ?</h5>
                      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-footer">
                        <form class="modal-form" action="{% url 'users:profile' user.pk %}" method="get">
                          <input type="hidden" name="remove-order" value="${order.number}">
                          <button type="submit" class="form-button">Да</button>
                          <button type="button" class="form-button" data-bs-dismiss="modal">Нет</button>
                        </form>
                    </div>
                  </div>
                </div>
            </div>
            <div class="order-price">
              <p> ${order.totalPrice}&#x20bd;</p>
            </div>
          </div>`)
          order.products.forEach(function (product) {
            $('#order-'+order.number).append(`
              <a>${product.title}</a>
            `)
          })
      })
    })

</script>
{% endblock %}