app/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users'))
]

handler404 = views.page_not_found

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('prices/', views.prices, name='prices'),
    path('new-order/', views.NewOrderView.as_view(), name='new-order'),
    path('contacts/', views.contacts, name='contacts'),
    path('accept/', views.AcceptOrderView.as_view(), name='accept'),
    path('accept/done/', views.AcceptOrderDoneView.as_view(), name='accept-done')
]

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView
from django.urls import path, reverse_lazy

from users import views
from users.views import UserPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('registration/', views.AuthRegistrationView.as_view(), name='registration'),
    path('logout/', views.logout, name='logout'),
    path('profile/<pk>', views.UserProfileView.as_view(), name='profile'),
    path('password-reset/', views.UserPasswordResetView.as_view(), name='password-reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password-reset-done.html'
         ),
         name='password-reset-done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password-reset-confirm.html',
            success_url=reverse_lazy('users:password-reset-complete')
         ),
         name='password-reset-confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password-change-done.html'
         ),
         name='password-reset-complete'),

    path('password-change/',
         UserPasswordChangeView.as_view(
             template_name='users/password-change-form.html'
         ),
         name='password-change'),

    path('password-change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password-change-done.html'
         ),
         name='password-change-done'),
]

main/infrastructure/models.py
from django.db import models
from datetime import datetime

from phonenumber_field.modelfields import PhoneNumberField

from main.domain.aggregates import Order
from main.domain.entities import Product
from users.models import UserModel


class ProductModel(models.Model):
    code = models.CharField(verbose_name='Код')
    name = models.CharField(verbose_name='Товар')
    price = models.IntegerField(verbose_name='Цена')
    title = models.CharField(verbose_name='Название')
    description = models.CharField(verbose_name='Описание', default='...')

    class Meta:
        db_table = 'product'
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = 'pk',

    def __str__(self):
        return self.title

    def to_domain(self) -> Product:
        return Product(
            id=self.pk,
            code=self.code,
            name=self.name,
            price=self.price,
            title=self.title,
            description=self.description
        )

    @staticmethod
    def from_domain(product: Product) -> 'ProductModel':
        return ProductModel(
            id=product.id,
            code=product.code,
            name=product.name,
            price=product.price,
            title=product.title,
            description=product.description
        )


class OrderModel(models.Model):
    STATUS = {
        ('Оформлен', 'Оформлен'),
        ('В работе', 'В работе'),
        ('Исполнен', 'Исполнен')
    }

    order_id = models.IntegerField(verbose_name='Номер заказа')
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='orders'
    )
    phone_number = PhoneNumberField(region='RU', verbose_name='Телефон')
    total_price = models.IntegerField('Общая цена')
    date = models.DateTimeField(verbose_name='Дата', default=datetime.utcnow)
    status = models.CharField(verbose_name='Статус', choices=STATUS, default='Оформлен')
    products = models.ManyToManyField(ProductModel)

    class Meta:
        db_table = 'order'
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ['-date']

    def __str__(self):
        return str(self.order_id)

    def __iter__(self):
        for field in self._meta.fields:
            title = field.verbose_name
            if title not in ['ID', 'Дата', 'Номер заказа']:
                yield title, field.value_to_string(self)

    def to_domain(self, email: str) -> Order:
        return Order(
            number=self.order_id,
            phone_number=str(self.phone_number),
            user_id=self.user.pk,
            email=email,
            total_price=self.total_price,
            status=self.status,
            products=[product.to_domain() for product in self.products.all()],
            date=self.date
        )

    @staticmethod
    def from_domain(order: Order) -> 'OrderModel':
        order_model = OrderModel(
            order_id=order.number,
            phone_number=order.phone_number,
            user=UserModel.objects.get(pk=order.user_id),
            status=order.status,
            total_price=order.total_price,
            date=order.date
        )
        return order_model


class MenuModel(models.Model):
    name = models.CharField(verbose_name='Название')
    url = models.CharField(verbose_name='Ссылка')

    class Meta:
        db_table = 'menu'
        verbose_name = 'меню'


class ContactModel(models.Model):
    title = models.CharField()
    str_image = models.CharField()
    value = models.CharField()

    class Meta:
        db_table = 'contact'
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('pk',)

main/models.py
from django.db import models
from datetime import datetime

from phonenumber_field.modelfields import PhoneNumberField

from users.models import User


class ProductModel(models.Model):
    code = models.CharField(verbose_name='Код')
    name = models.CharField(verbose_name='Товар')
    price = models.IntegerField(verbose_name='Цена')
    title = models.CharField(verbose_name='Название')
    description = models.CharField(verbose_name='Описание', default='...')

    class Meta:
        db_table = 'product'
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = 'pk',

    def __str__(self):
        return self.title


class OrderModel(models.Model):
    STATUS = {
        ('Оформлен', 'Оформлен'),
        ('В работе', 'В работе'),
        ('Исполнен', 'Исполнен')
    }

    order_id = models.IntegerField(verbose_name='Номер заказа')
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='orders'
    )
    phone_number = PhoneNumberField(region='RU', verbose_name='Телефон')
    total_price = models.IntegerField('Общая цена')
    date = models.DateTimeField(verbose_name='Дата', default=datetime.utcnow)
    status = models.CharField(verbose_name='Статус', choices=STATUS, default='Оформлен')
    products = models.ManyToManyField(ProductModel)

    class Meta:
        db_table = 'order'
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ['-date']

    def __str__(self):
        return str(self.order_id)

    def __iter__(self):
        for field in self._meta.fields:
            title = field.verbose_name
            if title not in ['ID', 'Дата', 'Номер заказа']:
                yield title, field.value_to_string(self)


class MenuModel(models.Model):
    name = models.CharField(verbose_name='Название')
    url = models.CharField(verbose_name='Ссылка')

    class Meta:
        db_table = 'menu'
        verbose_name = 'меню'


class ContactModel(models.Model):
    title = models.CharField()
    str_image = models.CharField()
    value = models.CharField()

    class Meta:
        db_table = 'contact'
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('pk',)

main/forms.py
from django import forms

from phonenumber_field.formfields import PhoneNumberField


class NewOrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(NewOrderForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name == 'phone_number' and 'invalid' in field.error_messages:
                field.error_messages['invalid'] = 'Введите корректный номер телефона'

    phone_number = PhoneNumberField(label='Телефон', region='RU')
    bot_shop = forms.BooleanField(label='Бот-магазин', required=False)
    admin_panel = forms.BooleanField(label='Админ-панель', required=False)
    database = forms.BooleanField(label='База данных', required=False)

main/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import FormView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from app.settings import DEBUG
from logger import Logger
from main.application.services.commands.create_order import CreateOrder
from main.application.services.commands.get_order_numbers import GetOrderNumbers
from main.application.services.commands.send_email import SendEmailWithOrder
from main.application.services.services import CreateOrderService
from main.domain.entities import Product
from main.forms import NewOrderForm
from main.domain.aggregates import Order
from shared.infrastructure.uow import UnitOfWork, TestUnitOfWork


def index(request):
    return render(request, 'main/index.html', {'title': 'Telegram bots'})


def about(request):
    return render(request, 'main/about.html', {'title': 'О технологии'})


def prices(request):
    return render(request, 'main/prices.html', {'title': 'Цены'})


class NewOrderView(LoginRequiredMixin, FormView):
    form_class = NewOrderForm
    template_name = 'main/new-order.html'
    extra_context = {'title': 'Новый заказ'}

    def form_invalid(self, form):
        errors = form.errors.get_json_data()
        return JsonResponse({'errors': errors}, status=400)


class AcceptOrderView(LoginRequiredMixin, TemplateView):
    template_name = 'main/accept.html'
    uow = UnitOfWork() if not DEBUG else TestUnitOfWork()
    logger = Logger()
    get_order_numbers_command = GetOrderNumbers(logger)
    order_numbers = get_order_numbers_command(uow)

    def get(self, request, *args, **kwargs):
        try:
            order_number = str(Order.generate_order_number(self.order_numbers))
            request.session['order_number'] = order_number
            context = {
                'title': 'Оформление заказа',
                'order_number': order_number
            }
            return self.render_to_response(context)
        except Exception:
            self.logger.error(f'Ошибка на странице подтверждения заказа у пользователя: '
                              f'{self.request.user.email}')


class AcceptOrderDoneView(LoginRequiredMixin, TemplateView):
    template_name = 'main/accept-done.html'
    extra_context = {'title': 'Оформление заказа'}
    send_email_with_order = SendEmailWithOrder()
    uow = UnitOfWork() if not DEBUG else TestUnitOfWork()
    logger = Logger()
    create_order_command = CreateOrder(logger)
    create_order_service = CreateOrderService(
        create_order_command, send_email_with_order, uow, logger
    )

    def post(self, request, **kwargs):
        try:
            order_number = request.session['order_number']
            order = json.loads(request.POST['order'])
            order = Order.factory(
                number=order_number,
                phone_number=order['phone_number'],
                email=self.request.user.email,
                user_id=self.request.user.pk,
                products=[
                    Product.factory(
                        _id=item['id'],
                        code=item['code'],
                        price=item['price']
                    ) for item in order['products']
                ],
            )
            self.create_order_service.execute(order)
            self.extra_context.update({
                'order_number': order_number,
                'email': self.request.user.email,
            })
            return super().render_to_response({})
        except Exception:
            self.logger.error(f'Ошибка на странице создания заказа у пользователя '
                              f'{self.request.user.email}')


def contacts(request):
    return render(request, 'main/contacts.html', {'title': 'Контакты'})


def page_not_found(request, exception):
    return render(request, 'page404.html', status=404)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_about.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <div class="header-container">{{ title }}</div>
        <div class="tech-content-wrapper">
            <div class="tech-content first-content">
                <h2>Телеграм бот –</h2>
                <p>удобный</p>
                <p>сервис для</p>
                <p>оформления</p>
                <p>заказов</p>
            </div>
            <div class="second-content tech-content">
                <p>Бот представляет возможность взаимодействия с клиентами через набирающий популярность мессенджер <img src="{% static 'images/tg.png' %}" alt=""><b>Telegram</b>. Что делает процесс заказа удобным и доступным</p>
            </div>
            <div class="tech-content">
                <div class="tech-content-header"><span class="fa fa-check" aria-hidden="true"></span>Простота использования</div>
                <p>Телеграм бот имеет интуитивно понятный интерфейс, который позволяет пользователям удобно выбирать и заказывать товары</p>
            </div>
            <div class="tech-content right-content">
                <div class="tech-content-header"><span class="fa fa-check" aria-hidden="true"></span>Персонализция</div>
                <p>Бот может сохранять информацию о клиентах и их предпочтениях, что позволяет предлагать персонализированные предложения и рекомендации</p>
            </div>
            <div class="tech-content">
                <div class="tech-content-header"><span class="fa fa-check" aria-hidden="true"></span>Рассылки</div>
                <p>Имеется встроенный функционал создания рассылок, с помощью которых можно уведомлять клиентов о новых акциях</p>
            </div>
            <div class="tech-content last-content">
                <div class="tech-content-header"><span class="fa fa-check" aria-hidden="true"></span>Интеграция с платёжными системами</div>
                <p>Телеграм бот имеет возможность работать через интернет-эквайринг платёжных систем СбербанкPay, ЮКасса и Робокасса, что позволяет вашим клиентам безопасно совершать оплату заказов</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/accept-done.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_new_order.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container form-font">
        <div class="accept-wrapper form-font">
            <div>
                <p><b>Заказ №{{ order_number }} успешно оформлен</b></p>
                <p>Вся информация о заказе отправлена на Вашу почту</p>
                <p><span class="span-email">{{ email }}</span></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/accept.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_accept.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <div class="form-header form-font">
                Детали заказа
        </div>
        <div class="form-order-container form-font">
            <div class="order-number-title">
                <p>Заказ №{{ order_number }}</p>
            </div>
            <form class="form-accept" method="POST">
                {% csrf_token %}
                <table class="table table1 table-fill table-bordered">
                  <tbody>
                    <tr>
                      <td>Email</td>
                      <td id="email-field">{{ user.email }}</td>
                    </tr>
                    <tr>
                      <td>Телефон</td>
                      <td id="phone-field"></td>
                    </tr>
                  </tbody>
                </table>
                <table class="table table2 table-fill table-bordered">
                  <tbody id="prices-table">
                  </tbody>
                </table>
                <div class="form-accept-buttons">
                    <button class="form-button form-font button-back">Назад</button>
                    <button type="submit" class="form-button form-font">Оплатить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
  const order = JSON.parse(localStorage.getItem('order'))
  $('#phone-field').text(order.phone_number)
  $('form').submit(function (e) {
    e.preventDefault()
    const csrfToken = getCookie('csrftoken')
    $.ajax({
        data: {'order': JSON.stringify(order)} ,
        headers: {
          'X-CSRFToken': csrfToken
        },
        type: $(this).attr('method'),
        url: "{% url 'main:accept-done' %}",
        success: function () {
            window.location.replace('{% url 'main:accept-done' %}')
        }
    })
  })
  $('.button-back').click(function () {
      window.location.replace('{% url "main:new-order" %}');
  })
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = jQuery.trim(cookies[i]);
        if (cookie.startsWith(name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break
        }
      }
    }
    return cookieValue
  }
})
</script>
{% endblock %}

main/templates/main/base.html
{% load static %}
{% load main_tags %}
{% menu as menu %}

{% contact_list as contacts %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <title>{{ title }}</title>
</head>
<body>
    <div class="bd">
        <div class="main">
            <div class="nav-wrapper">
                <div class="drop">
                    <button class="menu-button">&#9776;</button>
                    <div class="nav-buttons">
                        <div class="border-first-btn"></div>
                        {% for item in menu %}
                            <a href="{% if not user.is_authenticated and item.name == 'Новый заказ' %}{% url 'users:login' %}{% else %}{% url item.url %}{% endif %}"
                               class="{% if item.name == title %}active disabled{% endif %}">{{ item.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="logo">
                    {% if not user.is_authenticated %}
                    <div class="auth-button">
                        <img src="{% static 'images/lock.png' %}">
                        <div class="nav-buttons auth-drop">
                            <div class="nav-buttons"><a href="{% url 'users:login' %}"
                                                        class="{% if title == 'Авторизация' %}active disabled{% endif %}">Вход</a></div>
                            <div class="nav-buttons"><a href="{% url 'users:registration' %}"
                                                        class="{% if title == 'Регистрация' %}active disabled{% endif %}">Регистрация</a></div>
                        </div>
                    </div>
                    {% else %}
                    <div class="auth-button form-font{% if title == 'Профиль' %} disabled{% endif %}">
                        <a href="{% url 'users:profile' user.pk %}"
                           title="Профиль"
                           class="{% if title == 'Профиль' %}active disabled{% endif %}">{{ user.username }}</a>
                    </div>
                    {% endif %}
                    <a href="{% url 'main:home' %}" title="Главная">Telegram bots</a>
                    <p>
                        <a class="logo-url" href="{% url 'main:home' %}"><img src="{% static 'images/tg.png' %}" alt="telegram-logo"></a>
                    </p>
                </div>
            </div>
            {% block content %}{% endblock %}
            {% block content-2 %}{% endblock %}
            <div class="footer-space"></div>
        </div>
        <footer>
            <div class="footer-wrapper-1">
                <div class="footer-container">
                    <p>МЕНЮ</p>
                    <ul>
                    {% for item in menu %}
                        <li><a href="{% url item.url %}"
                               class="{% if title == item.name %}disabled{% endif %}">{{ item.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="footer-container">
                    <p>КОНТАКТЫ</p>
                    {% for contact in contacts %}
                    <p><span class="{{ contact.str_image }}" aria-hidden="true"></span> {{ contact.title }}: {{ contact.value }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="footer-wrapper-2">
                <p>© Telegram-bots 2024 г.</p>
            </div>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block script %}{% endblock %}
</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_contacts.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <p class="contacts-title">Контакты</p>
        <div class="contacts-wrapper">
        {% for contact in contacts %}
            <div class="contacts-container">
                <div class="contacts-image">
                    <span class="{{ contact.str_image }}" aria-hidden="true"></span>
                </div>
                <div class="contacts-data">
                    <p class="contacts-data-title">{{ contact.title }}</p>
                    <p>{{ contact.value }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/new-order.html
{% extends 'main/base.html' %}
{% load static %}
{% load main_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_new_order.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <div class="form-header form-font">
            Новый заказ
        </div>
        <div class="form-container form-font">
            <form method="post">
                {% csrf_token %}
                <div class="input-wrapper">
                    <div class="input-label-container">
                        <p class="phone_number_field">
                            <label for="id_phone_number">Телефон:</label>
                        </p>
                            <div class="input-container">
                                <div>
                                    <span class="fa fa-volume-control-phone" aria-hidden="true"></span>
                                </div>
                                <input class="form-input"
                                       type="tel"
                                       name="phone_number"
                                       value=""
                                       required=""
                                       id="id_phone_number"
                                       placeholder="Телефон">
                        </div>
                    </div>
                </div>
                <div class="error">
                    <ul class="errorlist">
                        <li class="error-phone_number"></li>
                    </ul>
                </div>
                <div class="form-buttons-wrapper">
                    {% product_list as prices %}
                    {% for item in prices %}
                    {% if forloop.first %}
                    <p>{{ item.title }} {{ item.price }} &#x20bd;</p>
                    <div class="form-func-title">Дополнительные функции</div>
                    <div class="form-buttons-container">
                        <div class="title-container">
                    {% else %}
                            <p>{{ item.title }} {{ item.price }} &#x20bd;</p>
                    {% endif %}
                    {% endfor %}
                        </div>
                        <div class="buttons">
                            {% for item in prices %}
                            {% if item.name != "bot_shop" %}  
                            <p>
                                <label class="checkbox-green">
                                <input type="checkbox" name="{{ item.name }}" id="id_{{ item.name }}" class="product-checkbox">
                                <span class="checkbox-green-switch" data-label-on="On" data-label-off="Off"></span>
                                </label>
                            </p>
                            {% endif %}  
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <button type="submit" class="form-button btn-next form-font">Далее</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
      const products = []
      {% product_list as products %}
      {% for product in products %}
        products.push({
          id: "{{ product.id }}",
          code: "{{ product.code }}",
          price: "{{ product.price }}",
          name: "{{ product.name }}"
        })
      {% endfor %}
      $('form').submit(function (e) {
        e.preventDefault()
        const orderProducts = []
        $('.product-checkbox').each(function () {
            if ($(this).prop("checked")) {
              const product = products.find((item) => item.name === $(this).attr("name"))
              orderProducts.push(product)
            }
        })
        const newOrder = {
          phone_number: $('#id_phone_number').val(),
          products: orderProducts
        }
        localStorage.setItem('order', JSON.stringify(newOrder))
        window.location.assign({% url 'main:accept' %})
      });
        
    })
</script>
{% endblock %}

main/templates/main/prices.html
{% extends 'main/base.html' %}
{% load static %}
{% load main_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_prices.css' %}">
{% endblock %}

{% block content %}
<div class="logo-wrapper">
    <div class="logo-container">
        <div class="container">
            <div class="package-container">
            {% product_list as products %}
            {% for product in products %}
              <div class="packages">
                <h1>{{ product.title }}</h1>
                <h2 class="text">{{ product.price|stringformat:"i"|add:".00" }} &#x20bd;</h2>
                <div class="list">
                  <p>{{ product.description }}</p>
                </div>
                <a href="{% url 'main:new-order' %}" class="button">Оформить заказ</a>
              </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}